### ISSUE TITLE
#Question: Event

### ISSUE THREAD

**Issue by rodrigolmacedo** [RodolfoBonis/DayCalendar#1]
Hi, awesome work! thanks for that!

1 - Can i override event widget to another? like card etc..
![image](https://user-images.githubusercontent.com/7695045/88465342-9cd86680-ce98-11ea-97dd-f6b109186e1b.png)
2 - Is possible to mark the current time(clock now) with red line?
![image](https://user-images.githubusercontent.com/7695045/88465344-a95cbf00-ce98-11ea-8f32-668cc62f576a.png)

**Comment by RodolfoBonis** [comment]
Hello, thanks for the feedback!

today it is not possible to do either.

but this can be implemented in future features.

**Comment by rodrigolmacedo** [comment]
its ok, already forked, i will try some stuffs ;)
