### ISSUE TITLE
Bug: when it is last day of the month, it will auto trigger onDateChange, and set the current date as day before the last day

### ISSUE THREAD

**Issue by function2000** [RodolfoBonis/DayCalendar#3]
For example: current date is 2021-03-31, it will  trigger onDateChange, and set date as 2021-03-30.  Please fix this bug. Thanks!

**Comment by function2000** [comment]
Attach picture here:
![page0](https://user-images.githubusercontent.com/4005363/113083061-1e457d00-920e-11eb-8797-99332cbc8cb8.png)
![page1](https://user-images.githubusercontent.com/4005363/113083069-243b5e00-920e-11eb-8df3-3925a92120de.png)

**Comment by RodolfoBonis** [comment]
Hello @function2000, Thanks for report, I will work on this problem

**Comment by RodolfoBonis** [comment]
Oh, and I will go implements Null-safety support as well

**Comment by function2000** [comment]
Thank you in advance!
You can check why 'i' equals 30 here, why not 31. See below:
![page2](https://user-images.githubusercontent.com/4005363/113085900-41bef680-9213-11eb-86ca-71bb9c702089.png)

**Comment by RodolfoBonis** [comment]
Apparently, this bug is caused when the number of pages in the page view is defined, I have already found the solution, tomorrow I will be releasing a hotfix to correct this problem before launching the null-safety version

**Comment by function2000** [comment]
> @function2000 I fixed the problem and published, please test the hotfix and if it is solved, let me know, I will close this issue
> 
> #5

It looks works now.  Thank you very much!
